### ISSUE TITLE
numpy version conflicts despite clean virtualenv

### ISSUE THREAD

**Issue by mattiasostmar** [alfredfrancis/ai-chatbot-framework#103]
I've installed virtualenv and created and activated a new virtualenv in the source folder.
I'm running Python 3.6.5 on a Mac OS X High Sierra 10.13.6.

When running `make run_dev` I get the following error:

```
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.umath failed to import
ImportError: numpy.core.umath failed to import
2018-08-11 14:54:46.402447: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr 
/bin/sh: line 1:  7848 Abort trap: 6           python run.py
make: *** [run_dev] Error 134
```
Since I run it in a virtualenv, I suppose the error is produced in ai-chatbot-framework and not in my own settings on my local computer? 

The numpy that gets installed on my computer running `make setup` is version 1.14.3, but I can't figure out what that RuntimeError is really saying, because I'm a noob.  

I tried
`pip uninstall numpy`
`pip install numpy --no_cache-dir`
to see if that helped, but it didn't.

**Comment by alfredfrancis** [comment]
We don't support python 3.6 yet. Please create a Py 2.7 virtualenv and try again.
