### ISSUE TITLE
Guys I can't build it

### ISSUE THREAD

**Issue by telostia** [alfredfrancis/ai-chatbot-framework#113]
Im using make setup and got errors.
First it asked me for setuptools-39.1.0, i then added setuptools-39.1.0 to requirements.txt then theres more errors regarding averaged_perceptron_tagger' not found, then I installed it and more errors...
I tried changing the files in requirements.txt to: flask_script==2.0.3
, spacy==2.0.11
tensorflow==1.9.0

but i now get : 
Failed to load nlu model. Maybe path /root/ai-chatbot-framework/model_files doesn't exist

Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from app import app
  File "/root/ai-chatbot-framework/app/__init__.py", line 33, in <module>
    from app.endpoint.controllers import endpoint
  File "/root/ai-chatbot-framework/app/endpoint/controllers.py", line 224, in <module>
    update_model(app, "Models updated")
  File "/root/ai-chatbot-framework/app/endpoint/controllers.py", line 212, in update_model
    app.config["MODELS_DIR"], app.config["USE_WORD_VECTORS"])
  File "/root/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py", line 588, in load
    return EmbeddingIntentClassifier()
  File "/root/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py", line 113, in __init__
    self.nlp = spacy.load('en')
  File "/root/ai-chatbot-framework/venv/local/lib/python2.7/site-packages/spacy/__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "/root/ai-chatbot-framework/venv/local/lib/python2.7/site-packages/spacy/util.py", line 119, in load_model
    raise IOError(Errors.E050.format(name=name))
IOError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by kamcik** [comment]
Hey, same here. Any progress on that ?

**Comment by alfredfrancis** [comment]
You need to install spacy en model. read [here](https://spacy.io/usage/models)

**Comment by telostia** [comment]
installed spacy en. stil shows errors.

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
--------------------------------------------------------------------------------
WARNING in starspace_intent_classifier [/root/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:587]:
Failed to load nlu model. Maybe path /root/ai-chatbot-framework/model_files doesn't exist

**Comment by telostia** [comment]
ok i see that it uses mongo db so I installed mongodb server and client(it wasnt listed on the main github requirements).
The results are now:

root@vps193677:~/ai-chatbot-framework# make run_dev
. venv/bin/activate && python run.py
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
--------------------------------------------------------------------------------
WARNING in starspace_intent_classifier [/root/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:587]:
Failed to load nlu model. Maybe path /root/ai-chatbot-framework/model_files doesn't exist
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in utils [/root/ai-chatbot-framework/app/endpoint/utils.py:25]:
loaded synonyms {}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in controllers [/root/ai-chatbot-framework/app/endpoint/controllers.py:220]:
Intent Model updated
--------------------------------------------------------------------------------
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
--------------------------------------------------------------------------------
WARNING in starspace_intent_classifier [/root/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:587]:
Failed to load nlu model. Maybe path /root/ai-chatbot-framework/model_files doesn't exist
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in utils [/root/ai-chatbot-framework/app/endpoint/utils.py:25]:
loaded synonyms {}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in controllers [/root/ai-chatbot-framework/app/endpoint/controllers.py:220]:
Intent Model updated
--------------------------------------------------------------------------------
 * Debugger is active!
 * Debugger PIN: xxx-xxx-xxx

**Comment by alfredfrancis** [comment]
It seems like you got it working. So, I'm closing the issue.
