### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by some81** [alfredfrancis/ai-chatbot-framework#116]
Hi there,
I tried to install your repo but I'm running into some issues.
I clone the repo and follow all the guidance for non docker installation.
I'm on Mac 
when I run make setup during the setup process  I run into this issue:
--------------------------------------------------------------------------------
WARNING in starspace_intent_classifier [/Users/atodorov/Desktop/Work/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:587]:
Failed to load nlu model. Maybe path /Users/atodorov/Desktop/Work/ai-chatbot-framework/model_files doesn't exist
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from app import app

**Comment by vinodalladi** [comment]
Dear Admin, Even im facing the same issue during setup process, im using Ubuntu 18.0+ and python 3.6. please help me

**Comment by madhupilla** [comment]
@vinodalladi 

i'm facing the same issue, could you please help me out.

Thanks in advance.

**Comment by lesyk** [comment]
@vinodalladi I love how politely you asked for help and how silently you are helping others.

**Comment by alfredfrancis** [comment]
@vinodalladi @madhupilla @lesyk 
The issue was due to some version mismatched in spacy and flask. It's fixed now.

**Comment by klsaudico** [comment]
i have the same problem
