### ISSUE TITLE
Error while initiating the Project

### ISSUE THREAD

**Issue by madhupilla** [alfredfrancis/ai-chatbot-framework#118]
@alfredfrancis 

docker-compose exec iky_backend python manage.py init

I'm getting the below error while initiating the project.

`WARNING in starspace_intent_classifier [/usr/src/app/app/nlu/classifiers/starspace_intent_classifier.py:587]:
Failed to load nlu model. Maybe path /usr/src/app/model_files doesn't exist
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in utils [/usr/src/app/app/endpoint/utils.py:25]:
loaded synonyms {}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in controllers [/usr/src/app/app/endpoint/controllers.py:220]:
Intent Model updated
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "manage.py", line 48, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 26, in init
    bot.save()
  File "/usr/local/lib/python2.7/site-packages/mongoengine/document.py", line 397, in save
    raise NotUniqueError(message % six.text_type(err))
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: iky-ai.bot index: name_1 dup key: { : "default" })`

Thanks in Advance.

**Comment by alfredfrancis** [comment]
fixed

**Comment by vijji90** [comment]
Hi, 

I am setting up the project without docker. I get below issue after executing make run_dev.
WARNING in starspace_intent_classifier [/mnt/c/Users/vpamidi/Documents/AI Studio/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:587]:
Failed to load nlu model. Maybe path /mnt/c/Users/vpamidi/Documents/AI Studio/ai-chatbot-framework/model_files doesn't exist
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in utils [/mnt/c/Users/vpamidi/Documents/AI Studio/ai-chatbot-framework/app/endpoint/utils.py:25]:
loaded synonyms {}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in controllers [/mnt/c/Users/vpamidi/Documents/AI Studio/ai-chatbot-framework/app/endpoint/controllers.py:220]:
Intent Model updated
--------------------------------------------------------------------------------
 * Debugger is active!
 * Debugger PIN: 198-470-455


After debugger pin, it is not going anywhere. Could you let me know if it is executing correctly?.

Thanks in advance.
