### ISSUE TITLE
How to connect Chatbot to other Database?

### ISSUE THREAD

**Issue by bigredbug47** [alfredfrancis/ai-chatbot-framework#124]
Hi @alfredfrancis ,

Thks for awesome project. I have practiced with your API integrating example, but can you suggest me how to connect data from my database that can interactive with your chatbot?

Ex:
When you ask 
"_How many dogs in cage?_"
Then the chatbot will get data from my database (PostgreSQL, MySQL, etc.), get value from column **number_dog** and will reply :
"_It's **%number_dog_value%** dogs in cage_" 

Thank a lot.

**Comment by bobland1** [comment]
Did you ever work out how to connect it to a different database? I Wish to connect to my MS SQL database

**Comment by alfredfrancis** [comment]
You can connect to different databases via REST API
