### ISSUE TITLE
Failed to load nlu model

### ISSUE THREAD

**Issue by npscode** [alfredfrancis/ai-chatbot-framework#132]
I am running below command but getting error. Please help what could be the reason..

python manage.py install_nltk_dependencies
--------------------------------------------------------------------------------
WARNING in starspace_intent_classifier [/var/www/html/chatBot-NLP/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:587]:
Failed to load nlu model. Maybe path /var/www/html/chatBot-NLP/ai-chatbot-framework/model_files doesn't exist
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from app import app
  File "/var/www/html/chatBot-NLP/ai-chatbot-framework/app/__init__.py", line 34, in <module>
    from app.endpoint.controllers import endpoint
  File "/var/www/html/chatBot-NLP/ai-chatbot-framework/app/endpoint/controllers.py", line 228, in <module>
    update_model(app, "Models updated")
  File "/var/www/html/chatBot-NLP/ai-chatbot-framework/app/endpoint/controllers.py", line 218, in update_model
    synonyms = get_synonyms()
  File "/var/www/html/chatBot-NLP/ai-chatbot-framework/app/endpoint/utils.py", line 21, in get_synonyms
    for entity in Entity.objects:
  File "/var/www/html/chatBot-NLP/ai-chatbot-framework/venv/lib/python3.7/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/var/www/html/chatBot-NLP/ai-chatbot-framework/venv/lib/python3.7/site-packages/mongoengine/document.py", line 219, in _get_collection
    if cls._meta.get("auto_create_index", True) and db.client.is_primary:
  File "/var/www/html/chatBot-NLP/ai-chatbot-framework/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1005, in is_primary
    return self._server_property('is_writable')
  File "/var/www/html/chatBot-NLP/ai-chatbot-framework/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 830, in _server_property
    writable_server_selector)
  File "/var/www/html/chatBot-NLP/ai-chatbot-framework/venv/lib/python3.7/site-packages/pymongo/topology.py", line 235, in select_server
    address))
  File "/var/www/html/chatBot-NLP/ai-chatbot-framework/venv/lib/python3.7/site-packages/pymongo/topology.py", line 193, in select_servers
    selector, server_timeout, address)
  File "/var/www/html/chatBot-NLP/ai-chatbot-framework/venv/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused

**Comment by alfredfrancis** [comment]
> pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused

You need to have a running mongodb instance

**Comment by alfredfrancis** [comment]
Also NLTK dependencies are removed from the platform. Please use the latest master branch

**Comment by npscode** [comment]
My Bad, That part is sorted now. thanks for the help.

One thing: will it support tensorflow2 as i can see few warnings once i executed migrate command:
However Training models finished successfully.

Trace is below:

python manage.py migrate
--------------------------------------------------------------------------------
WARNING in starspace_intent_classifier [/var/www/html/chatBot-NLP/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:587]:
Failed to load nlu model. Maybe path /var/www/html/chatBot-NLP/ai-chatbot-framework/model_files doesn't exist
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in utils [/var/www/html/chatBot-NLP/ai-chatbot-framework/app/endpoint/utils.py:25]:
loaded synonyms {}
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
INFO in controllers [/var/www/html/chatBot-NLP/ai-chatbot-framework/app/endpoint/controllers.py:224]:
Intent Model updated
--------------------------------------------------------------------------------
Created default bot
Imported 3 Stories
Training models..
--------------------------------------------------------------------------------
DEBUG in starspace_intent_classifier [/var/www/html/chatBot-NLP/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:479]:
Check if num_neg 10 is smaller than number of intents 2, else set num_neg to the number of intents - 1
--------------------------------------------------------------------------------
WARNING:tensorflow:From /var/www/html/chatBot-NLP/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:485: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /var/www/html/chatBot-NLP/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:492: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /var/www/html/chatBot-NLP/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:272: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From /var/www/html/chatBot-NLP/ai-chatbot-framework/venv/lib/python3.7/site-packages/tensorflow_core/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /var/www/html/chatBot-NLP/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:273: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
WARNING:tensorflow:From /var/www/html/chatBot-NLP/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:323: The name tf.losses.get_regularization_loss is deprecated. Please use tf.compat.v1.losses.get_regularization_loss instead.

WARNING:tensorflow:From /var/www/html/chatBot-NLP/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:497: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /var/www/html/chatBot-NLP/ai-chatbot-framework/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /var/www/html/chatBot-NLP/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:500: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-04-30 13:25:49.013575: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-30 13:25:49.034762: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1800000000 Hz
2020-04-30 13:25:49.035529: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d66942bbb0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-30 13:25:49.035553: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /var/www/html/chatBot-NLP/ai-chatbot-framework/app/nlu/classifiers/starspace_intent_classifier.py:368: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.
