### ISSUE TITLE
After clicking on Build Agent Reloads continuously 

### ISSUE THREAD

**Issue by surya-vamsi2310** [alfredfrancis/ai-chatbot-framework#134]
After i train my intents in List of Intents page, im getting continuous reloading of page.
and throws error.
![image](https://user-images.githubusercontent.com/59705196/81838203-70809f80-9563-11ea-84b7-1705892224dd.png)

**Comment by obulrdy6881** [comment]
even I got the same issue, when I run python manage.py migrate it shows below error
![Screenshot (56)](https://user-images.githubusercontent.com/62610390/81856071-df6af200-957d-11ea-89cb-1abbb6f21c3c.png)

**Comment by alfredfrancis** [comment]
> After i train my intents in List of Intents page, im getting continuous reloading of page.
> and throws error.
> ![image](https://user-images.githubusercontent.com/59705196/81838203-70809f80-9563-11ea-84b7-1705892224dd.png)

please post your python server logs

**Comment by alfredfrancis** [comment]
> even I got the same issue, when I run python manage.py migrate it shows below error
> ![Screenshot (56)](https://user-images.githubusercontent.com/62610390/81856071-df6af200-957d-11ea-89cb-1abbb6f21c3c.png)

Looks like you are using an older version. Please pull latest master branch from github and try again
