### ISSUE TITLE
failed docker run ...

### ISSUE THREAD

**Issue by msalam72** [alfredfrancis/ai-chatbot-framework#137]
Hi,
when I do
docker run --name=iky_backend --link mongo:3.6 -e="APPLICATION_ENV=Production" iky_backend:2.0.0

I get 
gunicorn run:app --bind 0.0.0.0:8080 --access-logfile=logs/gunicorn-access.log --error-logfile logs/gunicorn-error.log
make: *** [Makefile:21: run_docker] Error 3

Any advice?
Thanks

**Comment by kmkwon94** [comment]
I have same error

**Comment by alfredfrancis** [comment]
Fixed in latest master
