### ISSUE TITLE
make file error while running iky_backend container (windows)

### ISSUE THREAD

**Issue by khrv1695** [alfredfrancis/ai-chatbot-framework#138]
Hi,

I'm getting error in the make file, when I'm running docker container using the command :
 _docker run --name=iky_backend --link mongodb:mongodb -e="APPLICATION_ENV=Production" iky_backend:2.0.0_
**Makefile:16: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.**

**Comment by msalam72** [comment]
khrv1695,
you need to to do the following:
1- update makefile and replace line 16 spaces with tab
setup_spacy:
        . venv/bin/activate && python -m spacy download en_core_web_md && python -m spacy link en_core_web_md en
1- start over and Build again

**Comment by kmkwon94** [comment]
> khrv1695,
> you need to to do the following:
> 1- update makefile and replace line 16 spaces with tab
> setup_spacy:
> . venv/bin/activate && python -m spacy download en_core_web_md && python -m spacy link en_core_web_md en
> 1- start over and Build again

Could your explain more please? 
I replace line 16 spaces with tab. But I get same error.

**Comment by alfredfrancis** [comment]
Fixed in latest master
