### ISSUE TITLE
after running docker command getting Makefile:16: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.

### ISSUE THREAD

**Issue by surya-vamsi2310** [alfredfrancis/ai-chatbot-framework#141]
![image](https://user-images.githubusercontent.com/59705196/82831379-e971e680-9ed5-11ea-828b-ab12d82ca8d1.png)

**Comment by alfredfrancis** [comment]
You have to get the latest code and try

**Comment by surya-vamsi2310** [comment]
i just pulled code @alfredfrancis

**Comment by alfredfrancis** [comment]
Fixed in latest master
