### ISSUE TITLE
Which Python file runs the chat.

### ISSUE THREAD

**Issue by turbocpt** [alfredfrancis/ai-chatbot-framework#145]
I need to know which python file runs the chat communication in the window. I need to print out the response between user and bot to a file. If you can assist it would be great!

**Comment by alfredfrancis** [comment]
https://github.com/alfredfrancis/ai-chatbot-framework/blob/39ebc58251aa476eaf90051e399f21f548daba5b/app/endpoint/controllers.py#L29

**Comment by turbocpt** [comment]
Thanks a mill. Let me have a look and see if I can find out which is user and which is bot,
