### ISSUE TITLE
Trouble understanding you

### ISSUE THREAD

**Issue by burnzzz** [alfredfrancis/ai-chatbot-framework#15]
After installing following your instructions (usinging it the docker way) I get on the start page and get the welcom message in a weird pronounciation. Sound more like dutch then english. When I try to answer I always get "sorry I cannot understand you ..." although pronounced in this funny (not english)  way.

What settings did I miss?

**Comment by alfredfrancis** [comment]
you have to go to manage stories menu and build your stories
