### ISSUE TITLE
issue while adding the intent

### ISSUE THREAD

**Issue by akshayagrawal927** [alfredfrancis/ai-chatbot-framework#152]
Hi @alfredfrancis ,

i am getting below error while trying to add the intent.

2022/02/07 05:57:28 [error] 8#8: *14 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: , request: "POST /gateway/intents/ HTTP/1.1", upstream: "[http://172.18.0.3:8080//intents/"](http://172.18.0.3:8080//intents/%22), host: "localhost:8080", referrer: "[http://localhost:8080/"](http://localhost:8080/%22)

iky_gateway    | 172.18.0.1 - - [07/Feb/2022:05:57:28 +0000] "POST /gateway/intents/ HTTP/1.1" 502 575 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" "-"

**Comment by alfredfrancis** [comment]
There is no error. It's just flask logs. 

You can start the angular frontend to see the admin panel. Refer to readme for more information.

**Comment by akshayagrawal927** [comment]
Should I have to refer to readme of front-end folder ?

**Comment by akshayagrawal927** [comment]
Hi Alfred,

Now i am able to do the ng serve. please refer below , but run.py is still giving error


(bot) C:\chatbot2\frontend>npm run ng serve



> frontend@0.0.0 ng C:\chatbot2\frontend
> ng "serve"



** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2022-01-11T06:52:39.708Z
Hash: 45e968bc0340962d0b89
Time: 16204ms
chunk {agent.module} agent.module.chunk.js () 1.05 MB [rendered]
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 52.2 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 549 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 167 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 15.7 MB [initial] [rendered]



webpack: Compiled successfully.
webpack: Compiling...
Date: 2022-01-11T06:53:38.396Z - Hash: 2982121487e53770bc17 - Time: 1208ms
6 unchanged chunks



webpack: Compiled successfully.




---------------------------------------
while running pytohn run.py
C:\chatbot2\frontend/dist/
127.0.0.1 - - [11/Jan/2022 12:30:36] "GET / HTTP/1.1" 404 -

**Comment by alfredfrancis** [comment]
> Hi @alfredfrancis ,
> 
> i am getting below error while trying to add the intent.
> 
> 2022/02/07 05:57:28 [error] 8#8: *14 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: , request: "POST /gateway/intents/ HTTP/1.1", upstream: "[http://172.18.0.3:8080//intents/"](http://172.18.0.3:8080//intents/%22), host: "localhost:8080", referrer: "[http://localhost:8080/"](http://localhost:8080/%22)
> 
> iky_gateway | 172.18.0.1 - - [07/Feb/2022:05:57:28 +0000] "POST /gateway/intents/ HTTP/1.1" 502 575 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" "-"

Looks like your backend is not up. Are you using docker setup ?

**Comment by akshayagrawal927** [comment]
Yes

**Comment by alfredfrancis** [comment]
Please use docker-compose setup as mentioned [here](https://github.com/alfredfrancis/ai-chatbot-framework#using-docker-compose-recommended). If you still face any error, please comment here with the output of `docker-compose logs` command.

**Comment by alfredfrancis** [comment]
Fixed in latest master branch
