### ISSUE TITLE
iky_backend exited with code 3

### ISSUE THREAD

**Issue by igmer** [alfredfrancis/ai-chatbot-framework#153]
I'm getting error with docker compose: iky_backend exited with code 3

docker los says: 

     /usr/local/lib/python3.9/site-packages/spacy/util.py:738: UserWarning: [W094] Model 'en_core_web_md' (2.2.5) specifies an under-     constrained spaCy version requirement: >=2.2.2. This can lead to compatibility problems with older versions, or as 
     new spaCy versions are released, because the model may say it's compatible when it's not. Consider changing the "spacy_version" in your meta.json to a version range, with a lower and upper pin. For example: >=3.1.1,<3.2.0

How can I solve?

**Comment by akshayagrawal927** [comment]
Hi Igmer,

did you got the solution for it ?
