### ISSUE TITLE
how can I run this correctly?

### ISSUE THREAD

**Issue by kyungsoo-fininsight** [alfredfrancis/ai-chatbot-framework#154]
Hi, 
First of all, I was impressed with your great job! you did good job!
but nothing happened to me after following the step.
I clicked import button after setting 'default_intents.json file' in the setting as below
<img width="678" alt="image" src="https://user-images.githubusercontent.com/62061305/161648807-345dd67f-33c5-4ecd-8d3b-07d3719243d3.png">

then I tried test in the chat but it seems not to work correctly

<img width="323" alt="image" src="https://user-images.githubusercontent.com/62061305/161649144-753c808c-455b-44d1-a04a-37fb58e25ee3.png">

did I missing something?
I made new intent but still it doesn't work

**Comment by alfredfrancis** [comment]
Did you create a new intent for the can booking? It doesn't come with the default intents.
