### ISSUE TITLE
What is the maximum amount of data you tested?

### ISSUE THREAD

**Issue by narnikgamarnikus** [alfredfrancis/ai-chatbot-framework#16]
Hello, 
https://github.com/gunthercox/ChatterBot/issues

I tried [Chatterbot](https://github.com/gunthercox/ChatterBot) for serious production purposes, and I had some difficulties in performance, after training on [Ubuntu dialog corpus](http://dataset.cs.mcgill.ca/ubuntu-corpus-1.0/), what I wrote about here - https://github.com/gunthercox/ChatterBot/issues/839

Their parsing algorithm was built to find a more accurate answer, because of what it was passed recursively on the data structure, which greatly slowed down the response (sometimes it took a minute and a half or more)

I'm interested in the amount of data you actually encountered.

**Comment by alfredfrancis** [comment]
Training may take a considerable amount of time depending upon the amount of your training data. But once your trained model, the prediction is supposed to be super fast.
