### ISSUE TITLE
hi, how to support chinese

### ISSUE THREAD

**Issue by WildDylan** [alfredfrancis/ai-chatbot-framework#18]
hi, how to support chinese

**Comment by alfredfrancis** [comment]
You can use Stanford libraries for Chinese support,

> https://nlp.stanford.edu/projects/chinese-nlp.shtml
> http://www.nltk.org/_modules/nltk/tokenize/stanford_segmenter.html

Once you have features generated rest is language independent.

**Comment by WildDylan** [comment]
I will give a try.
