### ISSUE TITLE
How to upload a lot of data and train automatically?

### ISSUE THREAD

**Issue by narnikgamarnikus** [alfredfrancis/ai-chatbot-framework#20]
Hey.

I have 100 000 dialogues, not divided into topics and categories.

Is there any way how I can automatically give them all chatbot for training?

**Comment by alfredfrancis** [comment]
write a python script to insert those data directly into MongoDB
refer following

> https://github.com/alfredfrancis/ai-chatbot-framework/blob/master/app/train/controllers.py 

> https://github.com/alfredfrancis/ai-chatbot-framework/blob/master/app/stories/controllers.py

**Comment by narnikgamarnikus** [comment]
You write too obvious things, and too early to close the issue.

What I wanted to know is that there are no LabeledSentences in my dialogs, and I do not know how to properly break dialogs into Stories.

My issue to you was sent, precisely to clarify this.
