### ISSUE TITLE
Issue deploying via Heroku

### ISSUE THREAD

**Issue by jamestcg** [alfredfrancis/ai-chatbot-framework#24]
Hey - just letting you know the app fails to install on/using the Heroku link provided.  The error mentions that by using scipy, the app cannot be installed, pointing to: https://devcenter.heroku.com/articles/python-c-deps.
` !     Hello! It looks like you're trying to use scipy on Heroku.`
` !     Unfortunately, at this time, we do not directly support this library.`
` !     There is, however, a buildpack available that makes it possible to use it on Heroku.`
` !     You can learn more here:  https://devcenter.heroku.com/articles/python-c-deps`
` !     Sorry for the inconvenience.   -- Much Love, Heroku.`
` !     Push rejected, failed to compile Python app.`
` !     Push failed`

**Comment by alfredfrancis** [comment]
Add following build packs to app.json,

- https://github.com/heroku/exec-buildpack
- heroku/python

refer,
https://devcenter.heroku.com/changelog-items/670

**Comment by alfredfrancis** [comment]
fixed in [this commit](https://github.com/alfredfrancis/ai-chatbot-framework/commit/3a8bbc5932189d2fb741d0003a03eaadb019a437)

**Comment by scevola44** [comment]
@alfredfrancis I am having the same issue, even running the latest version. I checked `app.json` and the two build packs are listed
