### ISSUE TITLE
not working with mongodb with security enabled

### ISSUE THREAD

**Issue by sdonapar** [alfredfrancis/ai-chatbot-framework#25]
I get either authentication or authorization error when tried to connect to a mongodb that is started with security enabled. I have tried with various combinations in the config file and no luck.
DB_HOST="mongodb://username:password@host:port/database"
DB_HOST="mongodb://host:port" and DB_USERNAME="username" and DB_PASSORD="password"

Please let me know if there is any issue or I am not properly configuring the config.py

**Comment by alfredfrancis** [comment]
both should work. I've sucessfully used connection uri with security enabled.
we are using mongoengine for MongoDB connection. [This may help ](http://docs.mongoengine.org/guide/connecting.html)

**Comment by sdonapar** [comment]
Thanks for the confirmation, I will check and let you in case of any issues
