### ISSUE TITLE
Question - language support

### ISSUE THREAD

**Issue by Ncolaci** [alfredfrancis/ai-chatbot-framework#27]
Does the framework support spanish? Its possible to create stories and train those stories with intents in spanish?

**Comment by Ncolaci** [comment]
another question is... when i create 2 stories and the user input sentences are similar, the bot seems not to understand what response to show.

example: 
-story 1 sample user input: "i want to know about xxxx"
-story 2 sample user input: "i want to know about yyyy" 

both stories respond with default fallback intent.

i just write the input like the example above and click in start labeling, then add to test set and build the model.

i missing something?
how can i solve this?

**Comment by ZhartunMatthew** [comment]
I have the same question about russian language support. Is there a way, how to make bot understand russian?

**Comment by alfredfrancis** [comment]
@Ncolaci In your example, you created 2 stories for similar sentence. All you have to do is create single story for them and parameterize your xxxx and yyyy

And about Spanish support, you can use Stanford libraries from NLTK.

**Comment by Ncolaci** [comment]
@alfredfrancis ok, that works when the stories has the same speech response, but in this case speech response  must be different for each parameter.

as far as i know, i cant have 2 different speechs for a single story.
it is possible?

thx for the reply.

**Comment by alfredfrancis** [comment]
speech response can be retived from an API call. Based on your parameter you can have n number of responses.
https://www.youtube.com/watch?v=gqO69ojLobQ

**Comment by Ncolaci** [comment]
@alfredfrancis thanks a lot!
