### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by bertmsk** [alfredfrancis/ai-chatbot-framework#3]
In a sequence-labeler.py there's a line:

`# Extract Labeles from BIO tagged sentence`

But what exactly does it mean? Three types of different labels: B, I and O. "O" states for "other" or "dummy" or whatever, but what B and I means?

**Comment by alfredfrancis** [comment]
The standard way to do sequence labeling is the "BIO" encoding, where we label each word by "B-X", "I-X" or "O". Here, "B-X" means "begin a phrase of type X", "I-X" means "continue a phrase of type X" and "O" means "not in a phrase."
