### ISSUE TITLE
Add: build server

### ISSUE THREAD

**Issue by lesyk** [alfredfrancis/ai-chatbot-framework#33]
Add travis or something similar with
- autopep8
- pylint
setup

**Comment by alfredfrancis** [comment]
Don't we need to write test classes for that?

**Comment by lesyk** [comment]
Nope, just call autopre8 script.

**Comment by alfredfrancis** [comment]
That's just code formatting right? Do we really need it ?

**Comment by lesyk** [comment]
> That's just code formatting right?
More than that.

> Do we really need it ?
Yes

**Comment by alfredfrancis** [comment]
Ok. Let's do it.
Do you happen to have a sample .travis.yml configuration file for the same?

`language: python

python:
    - "2.7"
before_install:
    - pip install pep8
script:
    # Run pep8 on all .py files in all subfolders
    - find . -name \*.py -exec pep8 --ignore=E402 {} +
`

**Comment by lesyk** [comment]
Nope, I do not have. But code which you wrote looks in a way as I was assuming.

**Comment by alfredfrancis** [comment]
Ok. Let me try it out.
