### ISSUE TITLE
Last text box on the stories page is on the wrong place.

### ISSUE THREAD

**Issue by ZeroCool940711** [alfredfrancis/ai-chatbot-framework#35]
Hi there, i was testing your code and I found that the last text box on the "/stories/home" page is on the wrong place, I will add a screen capture to show you what I mean, maybe its because of my browser but no idea, would appreciate if you could fix it. Have a good day and thanks for the time.
![untitled](https://user-images.githubusercontent.com/5977640/31924976-330d9b84-b83a-11e7-80f2-0f2daf18f362.jpg)

**Comment by alfredfrancis** [comment]
looks like a browser specific issue. I'm not able to reproduce the issue. Can you please check in other browsers ?
