### ISSUE TITLE
I'm not able to serve you at the moment, please try again later

### ISSUE THREAD

**Issue by serlight1** [alfredfrancis/ai-chatbot-framework#37]
What i did:
1. Cloned repositories
2. sudo docker-compose build
3. sudo docker-compose up 

After that i navigate by url localhost:8001 and got fallowing issue:
_I'm not able to serve you at the moment, please try again later_

Log file with errors attached.
[gunicorn-error.log](https://github.com/alfredfrancis/ai-chatbot-framework/files/1421596/gunicorn-error.log)

**Comment by alfredfrancis** [comment]
Please follow the steps mentioned in the readme to restore initial training data from given database dump. Then build your model and try again.

**Comment by lesyk** [comment]
Just follow what is already there:
>After any of next methods, you will need to **import db**, and navigate to http://localhost:8001.

**Comment by serlight1** [comment]
Thank you. I done it, all works correctly now
