### ISSUE TITLE
Left pane not visible in stories/home.html - deployed on Heroku

### ISSUE THREAD

**Issue by awam** [alfredfrancis/ai-chatbot-framework#39]
The models are being trained but when I open https://murmuring-hollows-48177.herokuapp.com/ and manage stories, the left pane is completely empty. What could be the possible reason. Thank you.

**Comment by alfredfrancis** [comment]
I'm able to see the left pane with trained stories in your domain. If the issue still there, please try with a different browser or check if any api calls is getting blocked from your browser.

**Comment by awam** [comment]
I checked it in a different browser and it is working but the strange thing is that the left pane is visible when I open your app https://iky-ai.herokuapp.com/stories/home in the same browser but it doesn't show mine.

**Comment by awam** [comment]
In your domain, all the requests and responses are generated with https protocol while in mine some are generated with http. I have tried various method to force generation with https but nothing works.

**Comment by alfredfrancis** [comment]
i think there is some error returning from the api call to retrive stories. Check your browser console and server console to find out the issue.
