### ISSUE TITLE
Unable to Train or Build the created Story.

### ISSUE THREAD

**Issue by BabuNukala** [alfredfrancis/ai-chatbot-framework#4]
Alfred,

Thank you for the amazing framework. I have tried implementing your code but ran into an issue. Once after the setup is completed when I run I'm not able to see the Build/Train screen besides New Story. Also, I see  "I'm not able to serve you at the moment, please try again later" message in the chat screen.

Request you to review and provide your comments

![no build or train screen](https://cloud.githubusercontent.com/assets/26722450/26304461/be88d3ea-3eeb-11e7-9617-5c5894202434.png)

**Comment by alfredfrancis** [comment]
Did you used  docker-compose or manual setup ? if manual, check whether your mongodb instance is up and correct connection uri is given in the config file.

**Comment by BabuNukala** [comment]
I tried manually setting up the framework. I had an issue with MongoDB and after resolving it I can see the build and train screen. Yeah, I've rechecked the config file and the URI is correct.

But still the IKY shows the below message -
{
     "speechResponse": "I'm not able to serve you at the moment, please try again later"
}

**Comment by alfredfrancis** [comment]
Please check the log. Also check your javascript log in the console.
