### ISSUE TITLE
Trigger a Story and Validate Parameter

### ISSUE THREAD

**Issue by mariohmol** [alfredfrancis/ai-chatbot-framework#40]
Hi there, awesome framework, thank you!

I have some questions, see if you can help me on that:

1. The answer based on ajax call is very useful and thinking in that is it possible to make links and options there to user choose.. how you suggest to make this answer trigger another story.

2. How you suggest an way to validate a parameter.. for instance.. i ask a name and the user type like "i will not tell my name" or anything that is not a name.. so have a ajax call where i can validate true or false and make it prompt again case of false

One suggestion: Would be good to have a gitter channel so the comunity can help each other

One idea for future feature: Have prompt as array... so we can have different ways to ask and gives more the "human" feeling.. example.. name is a parameter and i can ask "What is your name?" "Can you tell me your name?"

Thanks!

**Comment by alfredfrancis** [comment]
Hi,
I'm glad you liked our product.

Let me answer your questions first,

1.  If you just want to trigger another story irrespective of the user input/answer, just introduce a new variable in story model pointing to the id of next story. And you can easily write necessary logic in the endpoint/controller to actually trigger that story.
If you want to conditionally trigger other stories based on some kind of rules or something, it'll be a bit more complicated involving some ML/NLP hacking.
2. There are two ways to validate your parameters,
     -  You can choose parameter type while you create the story and it'll be returned in the API result. You can introduce a javascript library to validate user inputs based on those types and do the validation in the frontend itself. And you can prompt the user to enter the correct input until the validation is successful.
     -  You can run the NER model on the user input and check whether required parameter type is present in the input. You can reuse existing NER code from repo itself(Using PyCRF Suite).

      The first method is easier to implement.

I've created a gitter channel for the project => https://gitter.im/ai-chatbot-framework

**Comment by mariohmol** [comment]
Thanks for the channel!

1. About to trigger a story based on user choice, what i had mind was:  Taking the example from the recipes, where in answer we have links to other pages... i guess that we could do buttons where calls a js function to type in the chat like 'next_story <answer>' 

2. Awesome, will do in the frontend.
