### ISSUE TITLE
Speech and Answer with HTML

### ISSUE THREAD

**Issue by mariohmol** [alfredfrancis/ai-chatbot-framework#42]
Hi,

reproducing your recipes example i could see that when i have an answer with html (ul and li) the speech kinds of get crazy (trys to translate the html).

Would be good to have a html strip where removes the html and extract the text to be available with voices.

thanks!

**Comment by alfredfrancis** [comment]
You can easily strip of the html tags in the fronted using JS before calling the text to speech function.
https://stackoverflow.com/questions/822452/strip-html-from-text-javascript
