### ISSUE TITLE
SciPy 0.17.1 won't install in windows 10

### ISSUE THREAD

**Issue by MaterialImplication** [alfredfrancis/ai-chatbot-framework#43]
`Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\john\\appdata\\local\\temp\\pip-build-_ntvkp\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\john\appdata\local\temp\pip-l_nw1f-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\john\appdata\local\temp\pip-build-_ntvkp\scipy\`

**Comment by alfredfrancis** [comment]
I recommend using the docker setup for windows as there will lot of such compactability issues.

**Comment by khoanpase61742** [comment]
you may try "virtualenv", it will help install python packages in virtual space and reduce conflicts when you try install new packages.

**Comment by lesyk** [comment]
@alfredfrancis you can close this: issue is not with your repo, but with SciPy. @MaterialImplication go to SciPy guys and ask there for help. Also, use docker and all problems will disappear.
