### ISSUE TITLE
"I'm not able to serve you at the moment, please try again later"

### ISSUE THREAD

**Issue by donnx32** [alfredfrancis/ai-chatbot-framework#45]
How do I fix this [problem](https://imgur.com/a/gvbL8), I can't make it work. I've tried it on two machines now. :thinking:

**Comment by alfredfrancis** [comment]
Make sure you have restored Database (ref Readme). If problem exists, post your gunicorn server log here

**Comment by donnx32** [comment]
@alfredfrancis Okay, it's fixed now. Thank you. [pic](https://imgur.com/a/bcmpg)

**Comment by donnx32** [comment]
@alfredfrancis However, I only used this line of code "mongorestore --drop --db=iky-ai --dir=dump/iky-ai/" I don't have docker on my machine and it appears it's still functioning. Is this acceptable? Won't I have future complications?

**Comment by alfredfrancis** [comment]
mongorestore is just a mongodb feature. It'll work irrespective of your installation type. No worries there.
