### ISSUE TITLE
Not able to predict based on the context

### ISSUE THREAD

**Issue by aditya542ar** [alfredfrancis/ai-chatbot-framework#5]
Alfred,

First of all thanks much for such an amazing framework.I have setup the framework manually and tried to train it as per the demo video provided by you.Everything worked fine. But when it asks for destination and I provide the same it says like "Sorry. I'm having trouble understanding you.", but in your demo it is working fine. 

Can you please suggest if any thing I am missing or I need to setup.
Below is the screenshot of the conversation.
![image](https://cloud.githubusercontent.com/assets/28903588/26367969/e37c3598-400d-11e7-9d97-8197fd1efeef.png)

**Comment by hjjobs** [comment]
hi aditya542ar how did you integrate your database ?? when i am trying to add manage stories then it does not get added there . what to do??
and can you tell me exact steps for running this

**Comment by aditya542ar** [comment]
Hi hjjobs,
As mentioned in the README file I have followed the below steps to setup the project.
First you need to install MongoDB and start mongoDB server.
Then configure the host and port of mongoDB in config.py and then run the following command.
`python setup.py`

This will create the database in mongoDB and insert some necessary records.

After this you can run the below comand to start the server.
`python run.py`

**Comment by aditya542ar** [comment]
Hey Alfred,

Nevermind. I finally figured out the issue in my case. It was due to some javascript error. Now I am able to run the demo successfully. Thanks much :)
