### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by knkarthik** [alfredfrancis/ai-chatbot-framework#56]
Amazing work! It would be helpful if you can explain how the tool works - the ML/NLP stuff behind this so that others can modify it if needed.

Thanks.

**Comment by alfredfrancis** [comment]
We have two main NLU modules

## Intent classifier module
It uses scikit learn SVM for text classification and uses NLTK for preprocessing and feature extraction.

Following preprocessing tasks are performed for the classification,
- Tokenizing
-  stopwords removal
-  Stemming
-  Lemmatizing

## NER module
NER module uses PyCRF suite for Named Entity Recognition.
It takes following features,
- POS tags
- Word order
Word position in the sentence
