### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'  in app/stories/controllers.py", line 82, in updateStory

### ISSUE THREAD

**Issue by marlonleite** [alfredfrancis/ai-chatbot-framework#62]
Hello, 
Its application is very cool. Thank you for having documented and provided this to us.
So,
I tested every application in the macos and everything worked perfectly. But I'm having trouble using this on ubuntu server in the production environment. Everything was installed with nginx, supervised, mongodb and virtualenv. The problem occurs when I try to update Story information. The updateStory function gives TypeError error: the JSON object must be str, not 'bytes'. I've tried converting json to utf-8 but the error remains. Some help is welcome. Thank you

**Comment by marlonleite** [comment]
OK,
after many attempts I was able to correct the error. Actually this has to do with python 3.5 on ubuntu. In macos the version of python is 3.6.

To fix the error, just add in the jsondata variable as_text = True.

jsondata = loads (request.get_data (as_text = True))

This is to allow the updateStory method of the correct parser in json.

Anyway the application is very cool. I would like to improve it for Brazilian Portuguese.

**Comment by alfredfrancis** [comment]
Cool. You are welcome to do a pull request for Portuguese.
