### ISSUE TITLE
Use of model_files

### ISSUE THREAD

**Issue by Chandrakala14** [alfredfrancis/ai-chatbot-framework#63]
Hi,

Very nice effort, I am having doubt in model_files. Inside that directory I was seen two files with the extension .model. Can you please tell me what that files actually having and how to view those file.

**Comment by alfredfrancis** [comment]
One is for intent classification, its a scikit learn SVM model.Other is for Entity recognition and its a CRFsuite model. We use them for prediction, you can't view them but they can be rebuilt using the framework.
