### ISSUE TITLE
Chatbox always returns 'I'm not able to serve you at the moment, please try again later'

### ISSUE THREAD

**Issue by LGnord** [alfredfrancis/ai-chatbot-framework#64]
I followed the following procedure
 1. clone the projet
 2. docker-compose build
 3. docker-compose up

Wait until those messages:
web_1      | Training models..
web_1      | Training models finished..

Then connect to http://localhost:8001/

I always get the same message:
"I'm not able to serve you at the moment, please try again later"

Thank for your help.

**Comment by alfredfrancis** [comment]
Did you [restore](https://github.com/alfredfrancis/ai-chatbot-framework#restore) the db ?
