### ISSUE TITLE
not able to restore dump

### ISSUE THREAD

**Issue by r6m3sh** [alfredfrancis/ai-chatbot-framework#65]
when i run "docker cp dump aichatbotframework_mongodb_1:/data/" in cmd , i am getting below error:
**Error response from daemon: No such container: aichatbotframework_mongodb_1**
can anyone help me here?

**Comment by alfredfrancis** [comment]
check your MongoDB container name using follwoing code

`docker ps | grep mongodb`

then use that name in

`docker cp dump <mongodb container name>:/data/`
