### ISSUE TITLE
Database is broken on heroku

### ISSUE THREAD

**Issue by juanzolo** [alfredfrancis/ai-chatbot-framework#66]
Not worth my time to try and fix the database being set to 127.0.0.1 on heroku.

**Comment by AdityaMIli** [comment]
seriously...fix the connection string =-=

**Comment by alfredfrancis** [comment]
MongoDB connection string dynamically generated in Heroku. You have to add it to your config.py
ref https://forum.freecodecamp.org/t/guide-for-using-mongodb-and-deploying-to-heroku/19347

**Comment by juanzolo** [comment]
Tacoz
