### ISSUE TITLE
Multi Bots and Protected endpoints

### ISSUE THREAD

**Issue by mariohmol** [alfredfrancis/ai-chatbot-framework#68]
Hi, 

i created a form to make it work with multi bots or single.

And when you create a bot you can set a user and password, where it can be used for manage the stories.

It works without protection as well. So i did something to have the same behaviour as today and supporting protected.

You can see here and make the PR as you wish
* https://github.com/mariohmol/ai-chatbot-framework

Have this changes implemented in angular component too

* https://github.com/mariohmol/ng-ai-chatbot

**Comment by alfredfrancis** [comment]
Waiting for your updated pull request as per our discussion
