### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by codeslord** [alfredfrancis/ai-chatbot-framework#71]
Could not train models..skipping.. (reason: 127.0.0.1:27017: [WinError 10061] No connection could be made because the target machine actively refused it)

**Comment by alfredfrancis** [comment]
make sure you have a MongoDB instance running and add your connection uri in config.py. follow the steps in readme

**Comment by codeslord** [comment]
Sure. I am not running from a docker instance. Will that be a problem?
Or is there a way I could implement the same thing with MySQL DB?
