### ISSUE TITLE
Cannot run the app

### ISSUE THREAD

**Issue by patrick-ckf** [alfredfrancis/ai-chatbot-framework#8]
I run the code on a docker tools on Windows 7.

Client:
Version: 17.05.0-ce
API version: 1.29
Go version: go1.7.5
Git commit 89658be
Built: Fri May 5 15:36:11 2017
OS/Arch: windows/amd64

Server:
Version: 17.05.0-ce
API version: 1.29 (minimum version 1.12)
Go version: go1.7.5
Git commit 89658be
Built: Thu May 4 21:43:09 2017
OS/Arch: linux/amd64
Experimental: false

Error response from daemon: create ./: "./" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed If you intended to pass a host directory, use absolute path.

**Comment by alfredfrancis** [comment]
Hi,
Please use absolute path instead of  -v ./:/app-container as docker CE does not take relative apth anymore
`
docker run --name=chabot-node-1  -e="APPLICATION_ENV=Production" -v /absolute/path/to/chatbot/folder/:/app-container -p 8001:8080 -it ai-chat-bot gunicorn --bind 0.0.0.0:8080 run:app`
