### ISSUE TITLE
How integrate Word2vec?

### ISSUE THREAD

**Issue by hadifar** [alfredfrancis/ai-chatbot-framework#83]
Hi @alfredfrancis,

I would like to contribute in the project. Could you please tell me, How you want to integrate word2vec (simple model like tfidf-word2vec or more complex neural network one)? Do you want to use spacy's word2vec?

**Comment by alfredfrancis** [comment]
@hadifar : did you get to take a look at this ?

**Comment by hadifar** [comment]
Hi @alfredfrancis,

Yes, I looked into the code.
Actually the `Rasa` implementation, also the referenced [paper](https://arxiv.org/abs/1709.03856), not using `word2vec` at all. The algorithm learn word/sentence embeddings at training time. `Rasa` authors, only used **Spacy** for tokenization and lemmatization in this case.

I try to look into it more carefully in next few days.

**Comment by alfredfrancis** [comment]
That's correct. But here I modified the code so that if enabled, it adds glove word vectors to the feature. Please check the code.

**Comment by hadifar** [comment]
According to the reference paper:

> An entity such as a document or a sentence can be described by a bag of words or n-grams, an entity such as a user can be described by the bag of documents...

So it seems reasonable to use word vectors as a feature. I found some advantage and disadvantage for using word vectors:

Assume we have an `intent` that contains two training example:

1.  I love cat
2. I like cat

If we use word vectors, then for new user input like "I entertain dog" ( does not have meaning just an example because of similar word vectors between `dog & cat` and `like & entertain`) it response to the user. If we not use word vector in this case, the system returns _I'm having trouble understanding you..._.
I think, It depends on what we expect from our system. more accuracy or more coverage.

Another thing that can be considered is `spacy.vector` return simple average of all word vectors which can be replaced with `word2vec with tf-idf weighting` that in most of the cases lead to better result.
