### ISSUE TITLE
Sequence of questions

### ISSUE THREAD

**Issue by patrick-ckf** [alfredfrancis/ai-chatbot-framework#9]
Did current framework, support user to ask sequence of questions?
like some kind of state management?

Or can I trigger another intent or story by api or set in UI?

Did current framework support some kind of logical handle?

Because we will have several questions with similar answer, eg. Yes or No. How can the bot determine, which answer is related which question?

**Comment by alfredfrancis** [comment]
As of now, there is no jumping between stories. But we do have support for maintaining states across stories through global context. 

This project is just a basic platform with Natural language understanding and basic actions. We'd like to have logical branching kind of features. Please do contribute.

**Comment by alfredfrancis** [comment]
As of now, there is no jumping between stories. But we do have support for maintaining states across stories through global context. 

This project is just a basic platform with Natural language understanding and basic actions. We'd like to have logical branching kind of features. Please do contribute.

**Comment by alfredfrancis** [comment]
and sequence of questions can be given as parameter prompts under a story.

**Comment by patrick-ckf** [comment]
How do the existing platforms perform maintaining states across stories through global context? Can you give me some examples?

**Comment by alfredfrancis** [comment]
Global context is possible if multiple stories/intents maintain uniform global entity names. You can have separate flags for identifying which entities goes into global context and which of them are to be updated over the time.
       For example if username is already input by one intent, it can be stored in global context and can be accessed from other stories when ever required. It can be replaced at some other time also. Similarly favorite color, location etc can be stored in global context once input.

**Comment by utsavagarwal444** [comment]
Hi Alfred, 
How would one go about storing input in global context to make it accessible by other stories?
Is there a better way to ask multiple questions and have an api call for each of those questions?
