### ISSUE TITLE
ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by tiancaipipi110** [alfredfrancis/ai-chatbot-framework#90]
running command `docker-compose up -d`

ERROR: for iky_gateway  Cannot start service iky_gateway: b'driver failed programming external connectivity on endpoint iky_gateway (ea8a0eabea09b3dad33c2840d7078990a4177a4a0f6a4596a271a329488380fc): Error starting userland proxy: Bind for 0.0.0.0:8080 failed: port is already allocated'
ERROR: Encountered errors while bringing up the project.

**Comment by alfredfrancis** [comment]
As the error says, port 8080 is already allocated. Update your docker-compose file with an available port and try again
