### ISSUE TITLE
Multiple Bot (agent)

### ISSUE THREAD

**Issue by hadifar** [alfredfrancis/ai-chatbot-framework#93]
Systems like DialogFlow and IBM can handle multiple instance of Chatbot ( or Agent). It would be great that `ai-chatbot-framework` can handle multiple agent. Do you have any idea to add this feature? 

Currently we have Bot collection that We can use `Intent` and `Entity` as embedded document to this collection ?

**Comment by hadifar** [comment]
#68

**Comment by alfredfrancis** [comment]
Supporting multiple Agents is really a great feature. But,  the goal of this project is to keep everything simple and straightforward for chatbot enthusiasts to learn and build on. Bringing something like multi-agent support is not something we want to do. Our focus should be to make this platform mature and powerful enough to create state-of-the-art chatbots. 

Even with the current setup, we can create multiple bots by creating multiple instances of the project.
