### ISSUE TITLE
Integration with RASA NLU

### ISSUE THREAD

**Issue by guru9493** [alfredfrancis/ai-chatbot-framework#94]
Just wondering if IKY is based on RASA NLU for underlying NLU. If not, is there any way where we can plug RASA NLU into IKY.

**Comment by alfredfrancis** [comment]
Iky is not based on Rasa NLU. But we provide a Rasa NLU implementation of Starspace intent classification option.

No, You cant plug and play Rasa NLU to iky. You'll have to modify the code inorder to do that.

**Comment by guru9493** [comment]
Ohh.. The examples mentioned seemed similar to that of Rasa NLU. Just
checking it. Nice work 👍
